bug(masked errors): add gateway specific errorhandling tests
Pocket/apollo-utils pull request #221
Opened 2023-03-08 13:38 UTC by cmharlow

## Goal

Repair gateway-specific masking errors and add some "integration" tests that reflect the HTTP-based, Javascript class-stripping issues of passing our custom Errors from the subgraph to the gateway.

Note: making PR and pushing tests alone first to confirm the capture the bad behavior of the gateway, then pushing a possible repair.

Issues:
* https://getpocket.atlassian.net/browse/INFRA-1041

## Notes:

In order to fully test this issue, I ran gateway and a few services (including shareable lists) locally. Here are some findings of the request & error responses being passed between the two:

### HTTP requests & responses

#### Shareable Lists API

```
RECV <<< POST / localhost {
  query: 'mutation Mutation__shareable_lists_api__0($data:CreateShareableListInput!){createShareableList(data:$data){title description status moderationStatus}}',
  variables: {
    data: {
      title: 'charlow-test5',
      description: 'making test public collections'
    }
  },
  operationName: 'Mutation__shareable_lists_api__0'
}
SEND >>> 200 {"errors":[{"message":"A list with the title \"charlow-test5\" already exists","locations":[{"line":1,"column":76}],"path":["createShareableList"],"extensions":{"code":"BAD_USER_INPUT","stacktrace":["UserInputError: A list with the title \"charlow-test5\" already exists","    at new CustomGraphQLError (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:30:9)","    at new UserInputError (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:71:9)","    at createShareableList (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/database/mutations/ShareableList.js:19:15)","    at async executeMutation (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/public/resolvers/mutations/utils.js:10:12)","    at async createShareableList (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/public/resolvers/mutations/ShareableList.js:7:12)"]}}],"data":{"createShareableList":null}}
```

#### Gateway / Client API

```
RECV <<< POST / localhost {
  operationName: 'Mutation',
  variables: {
    data: {
      title: 'charlow-test5',
      description: 'making test public collections'
    }
  },
  query: 'mutation Mutation($data: CreateShareableListInput!) {\n' +
    '  createShareableList(data: $data) {\n' +
    '    title\n' +
    '    description\n' +
    '    status\n' +
    '    moderationStatus\n' +
    '  }\n' +
    '}\n'
}
SEND >>> 200 {"errors":[{"message":"Internal server error","path":["createShareableList"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":{"createShareableList":null}}
```

### GraphQL Events Upon Mutation Request

#### Shareable Lists API

```
info: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"request","operationName":"Mutation__shareable_lists_api__0","query":"mutation Mutation__shareable_lists_api__0($data:CreateShareableListInput!){createShareableList(data:$data){title description status moderationStatus}}","variables":{"data":{"title":"charlow-test5","description":"making test public collections"}}}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"parsingDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"validationDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"didResolveOperation","operationName":"Mutation__shareable_lists_api__0"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"responseForOperation","response":{"http":{"headers":{}}}}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"executionDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
error: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"errors","errors":[{"message":"A list with the title \"charlow-test5\" already exists","locations":[{"line":1,"column":76}],"path":["createShareableList"],"extensions":{"code":"BAD_USER_INPUT"}}]}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"a79af572-b89a-43c8-acef-139c6a60dc59","event":"response"}, timestamp: 2023-03-06 20:40:23:4023 }
```

#### Client API

```
info: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"request","operationName":"Mutation","query":"mutation Mutation($data: CreateShareableListInput!) { createShareableList(data: $data) { title description status moderationStatus } } ","variables":{"data":{"title":"charlow-test5","description":"making test public collections"}}}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"parsingDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"validationDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"didResolveOperation","operationName":"Mutation"}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"responseForOperation","response":{"http":{"headers":{}}}}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"executionDidStart"}, timestamp: 2023-03-06 20:40:23:4023 }
error: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"errors","errors":[{"message":"A list with the title \"charlow-test5\" already exists","path":["createShareableList"],"extensions":{"code":"BAD_USER_INPUT","stacktrace":["UserInputError: A list with the title \"charlow-test5\" already exists","    at new CustomGraphQLError (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:30:9)","    at new UserInputError (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:71:9)","    at createShareableList (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/database/mutations/ShareableList.js:19:15)","    at async executeMutation (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/public/resolvers/mutations/utils.js:10:12)","    at async createShareableList (/Users/charlow/Work/src/github.com/pocket/shareable-lists-api/dist/public/resolvers/mutations/ShareableList.js:7:12)"],"serviceName":"shareable-lists-api"}}]}, timestamp: 2023-03-06 20:40:23:4023 }
debug: { message:{"id":"8dffe46b-4201-4074-983a-42b7c6de9243","event":"response"}, timestamp: 2023-03-06 20:40:23:4023 }
info: { message:{"id":"da508cdb-2183-489f-ba9e-09ffa828a2a0","event":"request","operationName":"IntrospectionQuery","query":"query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } } ","variables":{}}, timestamp: 2023-03-06 20:40:23:4023 }
```

### Manual Type Logging around Error

#### Shareable Lists API

formattedError value, type, & class instance: 
```
{
  messag [...]

2023-03-08 16:54 UTC, hyperparabolic requested changes
Great analysis. Super thorough. Test coverage looks great, too.

One tiny implementation nit.

2023-03-08 18:13 UTC, cmharlow commented on src/errorHandler/errorHandler.ts
> +    gatewayUnmaskedErrors.indexOf(error.extensions.code as string) > -1
yeah so trying to implement this reminded why I got to where I got to - I want to pass through a String, and if I just make a Set, it doesn't register as a Set of Strings, but as `const gatewayUnmaskedErrors: Set<InternalErrorCode | ApolloServerErrorCode>` - which blocks trying to find the extension code in it.

2023-03-08 18:43 UTC, cmharlow commented on src/errorHandler/errorHandler.ts
> +const gatewayUnmaskedErrors: string[] = [
i attempted a version of what i think you proposed here, though its not terribly different from the original in order to make string matching work.

2023-03-08 19:40 UTC, jpetto submitted a review, later dismissed
this looks good to me!

2023-05-11 18:47 UTC, cmharlow commented
closed in favor of https://github.com/Pocket/client-api/pull/348 as the temporary solution at the time.

2023-05-11 18:47 UTC, closed without merging